language: ruby
bundler_args: --without debug
script: "bundle exec rake ci"
cache: false 
rvm:
  - 2.1.3
  - 2.1.6
  - 2.2.3
  - 2.3.0
sudo: false
services:
  - redis-server
addons:
  code_climate:
    repo_token: 9b8c58a49bdfba5582d6a766fbe198e3720158e5e65c2ae00b1667e5e1bb8769
env: CI=yes
before_install:
  # TODO: fix https://issues.dp.la/issues/8556
  # Workaround modified from https://github.com/cbeer/engine_cart/issues/64
  - if [ $TRAVIS_RUBY_VERSION != "2.1.3" ]; then gem uninstall -i "/home/travis/.rvm/gems/ruby-$TRAVIS_RUBY_VERSION@global" bundler -v 1.13.0; fi
  - gem install bundler -v "~> 1.11.0"
matrix:
  allow_failures:
    - rvm: 2.1.6
    - rvm: 2.2.3
    - rvm: 2.3.0
