default:
  startup_wait: 90
  jetty_port: 8983
  java_opts:
    - "-XX:MaxPermSize=128m"
    - "-Xmx256m"
    - "-Dmarmotta.home=<%= MARMOTTA_HOME %>"
test:
  jetty_port: <%= ENV['TEST_JETTY_PORT'] || 8983 %>
  <%= ENV['TEST_JETTY_PATH'] ? "jetty_home: " + ENV['TEST_JETTY_PATH'] : '' %>