---
marmotta:
  base: 'http://localhost:8983/marmotta/'
  ldp: 'http://localhost:8983/marmotta/ldp'
  record_container: 'http://localhost:8983/marmotta/ldp/original_record'
  item_container: 'http://localhost:8983/marmotta/ldp/items'
  # read_timeout: Seconds to wait for marmotta's HTTP response.
  read_timeout: 360

elasticsearch:
  host: 'localhost:9200'
  # In testing, index_name refers to a temporary index created just for tests.
  index_name: 'dpla_test'

prov:
  activity: 'activity'
  provider_base: 'http://dp.la/api/contributor/'

solr:
  url: 'http://localhost:8983/solr/'