---
marmotta:
  base: 'http://localhost:8983/marmotta/'
  ldp: 'http://localhost:8983/marmotta/ldp'
  record_container: 'http://localhost:8983/marmotta/ldp/original_record'
  item_container: 'http://localhost:8983/marmotta/ldp/items'

prov:
  activity: 'activity'

solr:
  url: 'http://localhost:8983/solr/'