module Krikri::Harvesters

  class MarcXMLHarvester
    include Krikri::Harvester

    attr_reader :opts

    def initialize(opts = {})
      @max_records = opts.fetch(:max_records, :unlimited)
      super
    end

    ##
    # @return [Hash] A hash documenting the allowable options to pass to
    #   initializers.
    #
    # @see Krikri::Harvester::expected_opts
    def self.expected_opts
      {
        key: :marcxml,
        opts: {
          max_records: {type: :int, required: false},
        }
      }
    end

    ##
    # @see Krikri::Harvester#count
    def count
      raise NotImplementedError
    end

    ##
    # @return [Enumerator::Lazy] an enumerator of the records targeted by this
    #   harvester.
    def records
      enumerate_records.lazy.map { |rec| build_record(rec) }
    end

    ##
    # Gets a single record with the given identifier from the API
    #
    # @return [Enumerator::Lazy] an enumerator over the ids for the records
    #   targeted by this harvester.
    def record_ids
      enumerate_records.lazy.map { |rec| rec.identifier }
    end

    ##
    # @param identifier [#to_s] the identifier of the record to get
    # @return [#to_s] the record
    def get_record(identifier)
      raise NotImplementedError
    end

    ##
    # @return [String] the content type for the records generated by this
    #   harvester
    def content_type
      'text/xml'
    end

    private

    def enumerate_records
      record_count = 0

      Enumerator.new do |yielder|
        each_collection do |marcxml_io|
          Nokogiri::XML::Reader(marcxml_io).each do |node|
            if record_count == @max_records
              break
            end

            if node.name == 'record' && node.node_type == Nokogiri::XML::Reader::TYPE_ELEMENT
              yielder << MarcXMLDoc.new(node)
              record_count += 1
            end
          end
        end
      end
    end

    def build_record(marcxml_doc)
      @record_class.build(mint_id(marcxml_doc.identifier),
                          marcxml_doc.source,
                          content_type)
    end
  end


  class MarcXMLDoc

    attr_reader :identifier, :source

    def initialize(nokogiri_doc)
      @source = nokogiri_doc.outer_xml
      doc = Nokogiri::XML(@source)
      doc.remove_namespaces!

      @identifier = doc.xpath("//controlfield[@tag='001']").text
    end

  end

end
